import Head from "next/head";
import { Footer, Header, Testimonial } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Serene Products & Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header section */}
      <Header />

      {/* Landing section */}
      <div>
        {/* Left */}
        <div>
          <p>Safety first</p>
          <h1>Fire Equipment & Services</h1>
          <p>
            Serene products & services deals with sale, servicing and
            maintenance of fire engineering systems, generators, solar,
            electrical, safety audits and trainings
          </p>
        </div>

        {/* Right */}
        <img src="/favicon.ico" alt="landing" />
      </div>

      {/* Content */}
      <div>
        {/* What we do */}
        <div>
          <p>What we do</p>
          <div>
            {/* Left */}
            <div>
              <h1>Fire Systems & Safety Training</h1>
              <p>
                Serene products and servicing deals with sale, servicing and
                maintenance of fire engineering systems, generators, solar,
                electrical, safety audits and trainings.
              </p>
              <br />
              <p>
                We offer high quality fire products that are manufactured to
                international standards such as :
              </p>
              <br />
              <span>&bull; British Standards (BS)</span>
              <span>&bull; European Standards (BS)</span>
              <span>&bull; Underwriter Laboratory Standards</span>
              <span>&bull; Kenya Bureau of Standards (KEBS)</span>
            </div>

            {/* Right */}
            <div>
              <img src="/favicon.ico" alt="what_we_do_1" />
              <img src="/favicon.ico" alt="what_we_do_2" />
            </div>
          </div>
          <button>learn more</button>
        </div>

        {/* Products catalogue */}
        <div>
          <p>Products catalogue</p>
          <div>
            {[1, 2, 3].map((el) => (
              <div>
                <img src="/favicon.ico" alt={`product_${el}`} />
                <div>
                  <h1>Powdered fire extinguisher</h1>
                  <a href={`/products/#${el}`}>Learn more </a>
                </div>
              </div>
            ))}
          </div>

          <div>
            <button>see all products</button>
          </div>
        </div>

        {/* About Us */}
        <div>
          <p>About us</p>
          <h1>Our story</h1>
          <br />
          <p>
            Serene products & services deals with sale, servicing and
            maintenance of fire engineering systems, generators, solar,
            electrical, safety audits and trainings.. We supply business
            customers, public bodies and organizations but also welcome
            individual end customers. Customers receive perfect customer care
            from us whether they purchase one fire extinguisher or a thousand.
            This focus on saving customers money and offering good value with
            reliable nationwide customer service has won us new clients as well
            as recurring business from existing ones.
          </p>
        </div>
      </div>

      {/* Testimonials */}
      <div>
        <p>Testimonials</p>
        <h1>What our clients are saying</h1>
        <br />
        {[1, 2, 3].map((el) => (
          <Testimonial />
        ))}
      </div>

      {/* Footer */}
      <Footer />
    </div>
  );
}
